/*procedminento para ver los pagos de los clientes*/

CREATE OR REPLACE PROCEDURE lISTAR_DETALLE_PAGO (C_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
   OPEN C_CURSOR FOR
   SELECT p.ID_PAGO, p.ESTADO_PAGO,C.NOMBRE_TITULAR, C.RUT_EMPRESA  FROM PAGO P
   INNER JOIN CLIENTE ON P.ID_CLIENTE = C.ID_CLIENTE;
END lISTAR_DETALLE_PAGO;


/*Procedimiento para Cantidad de Accidentes*/
CREATE OR REPLACE PROCEDURE ACCIDENTES_POR_CLIENTE(C_ACCIDENTES OUT SYS_REFCURSOR)
IS
BEGIN
  OPEN C_ACCIDENTES FOR
    SELECT cl.ID_CLIENTE,cl.NOMBRE_TITUTAL,cl.RUT_EMPRESA,cl.NOMBRE_EMPRESA,COUNT(ac.ID_ACCIDENTE) AS "CANTIDAD_ACCIDENTES" FROM SOLICITUD so 
    INNER JOIN ACCIDENTE ac ON so.ID_SOLICITUD = so.ID_SOLICITUD
    INNER JOIN CLIENTE cl ON so.CLIENTE = cl.ID_CLIENTE
    GROUP BY cl.ID_CLIENTE,cl.NOMBRE_TITUTAL,cl.RUT_EMPRESA,cl.NOMBRE_EMPRESA;
END ACCIDENTES_POR_CLIENTE;
